name: OPA

on:
  workflow_call:

jobs:

  opa:

    runs-on: self-hosted

    container:
      image: ubuntu:latest

    steps:

      - name: Install Packages
        run: |
          apt-get update
          apt-get install -y \
            curl \
            tar \
            git

      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Install OPA
        run: |
          curl -L -o opa \
            https://openpolicyagent.org/downloads/latest/opa_linux_amd64_static

          chmod +x opa

          mv opa /usr/local/bin/

          opa version

      - name: Evaluate Policy
        run: |
          opa eval \
            -d policies \
            -i tfplan.json \
            "data.azure.naming"
