name: Terraform Validate

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string

    secrets:
      TF_API_TOKEN:
        required: true

jobs:

  validate:

    runs-on: self-hosted

    container:
      image: hashicorp/terraform:1.13

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

    steps:

      - uses: actions/checkout@v4

      - name: Init Without Backend
        working-directory: ${{ inputs.working_directory }}
        run: terraform init -backend=false

      - name: Validate
        working-directory: ${{ inputs.working_directory }}
        run: terraform validate