name: Terraform Plan

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string

    secrets:
      TF_API_TOKEN:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:

  plan:

    runs-on: self-hosted

    permissions:
      id-token: write
      contents: read
      
    environment: dev
    
    container:
      image: ubuntu:latest

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

    steps:

      - name: Install Base Packages
        run: |
          apt-get update
          apt-get install -y \
            curl \
            wget \
            unzip \
            tar \
            git \
            jq \
            ca-certificates \
            gnupg \
            lsb-release

      - uses: actions/checkout@v4

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | bash

      - name: Install Terraform
        run: |
          TERRAFORM_VERSION="1.13.0"

          wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip

          unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip

          mv terraform /usr/local/bin/

          terraform version

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Verify Azure Login
        run: |
          az account show

      - name: Terraform Init
        working-directory: ${{ inputs.working_directory }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ inputs.working_directory }}
        run: terraform plan -out=tfplan

      - name: Plan Json
        working-directory: ${{ inputs.working_directory }}
        run: terraform show -json tfplan > tfplan.json

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: |
            ${{ inputs.working_directory }}/tfplan
            ${{ inputs.working_directory }}/tfplan.json
