name: TFLint

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string

jobs:

  tflint:

    runs-on: self-hosted

    container:
      image: ghcr.io/terraform-linters/tflint:latest

    steps:

      - uses: actions/checkout@v4

      - name: Run TFLint
        working-directory: ${{ inputs.working_directory }}
        run: |
          tflint --init
          tflint --recursive