name: Terraform Pipeline

on:

  workflow_dispatch:

  pull_request:

  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:

  bootstrap:

    uses: ./.github/workflows/terraform-cloud-bootstrap.yml

    with:
      organization: HCL-TERRA-TEAM
      workspace_name: dev-workspace

    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

#  fmt:
#
#    needs: bootstrap-workspace
#
#    uses: ./.github/workflows/terraform-fmt.yml
#
#    with:
#      working_directory: network/env/dev

  validate:

    uses: ./.github/workflows/terraform-validate.yml

    with:
      working_directory: network/env/dev

    secrets: inherit

  tflint:

    needs: validate

    uses: ./.github/workflows/tflint.yml

    with:
      working_directory: network/env/dev

  trivy:

    needs: tflint

    uses: ./.github/workflows/trivy.yml

  terraform-test:

    needs: trivy

    uses: ./.github/workflows/terraform-test.yml

    with:
      working_directory: network/env/dev

    secrets: inherit

  plan:

    needs: terraform-test

    uses: ./.github/workflows/terraform-plan.yml

    with:
      working_directory: network/env/dev

    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  opa:

    needs: plan

    uses: ./.github/workflows/opa.yml

  manual-approval:

    needs: opa

    runs-on: ubuntu-latest

    environment: Manual-Approval-Task

    steps:

      - name: Waiting For Approval
        run: echo "Manual approval completed"

  apply:

    if: github.event_name == 'push' &&
        github.ref == 'refs/heads/main'

    needs:
      - manual-approval

    uses: ./.github/workflows/terraform-apply.yml

    with:
      working_directory: network/env/dev

    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
