name: Terraform Validate

on:
  workflow_call:

    inputs:

      module_name:
        required: true
        type: string

    secrets:

      TF_API_TOKEN:
        required: true

permissions:
  contents: read

jobs:

  validate:

    runs-on: self-hosted

    container:

      # Official Image
      # https://hub.docker.com/r/hashicorp/terraform
      image: hashicorp/terraform:1.13.0

    defaults:

      run:
        shell: sh

    env:

      TF_IN_AUTOMATION: true
      TF_INPUT: false
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Terraform Version
        run: terraform version

      - name: Terraform Init

        working-directory: ${{ inputs.module_name }}/example

        run: |

          terraform init \
            -input=false \
            -no-color

      - name: Terraform Validate

        working-directory: ${{ inputs.module_name }}/example

        run: |

          terraform validate -no-color

      - name: Workflow Summary

        if: always()

        run: |

          {
            echo "# Terraform Validate"
            echo ""
            echo "| Item | Value |"
            echo "|------|-------|"
            echo "| Module | ${{ inputs.module_name }} |"
            echo "| Result | ${{ job.status }} |"
          } >> $GITHUB_STEP_SUMMARY