name: Terraform Test

on:
  workflow_call:
    inputs:
      module_name:
        required: true
        type: string
        # Supports single or comma-separated module names
        # e.g. "resource-group" or "resource-group,virtual-network"

    secrets:
      TF_API_TOKEN:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  contents: read
  id-token: write

jobs:

  terraform-test:

    runs-on: self-hosted

    container:
      image: hashicorp/terraform:1.13
      options: --user 1000:1000

    defaults:
      run:
        shell: sh

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: true

    steps:

      - uses: actions/checkout@v4

      - name: Init and Test
        run: |
          echo "${{ inputs.module_name }}" | tr ',' '\n' | while IFS= read -r module; do
            module=$(echo "$module" | tr -d ' ')

            terraform -chdir="${module}" init -backend=false

            terraform -chdir="${module}" test
          done