name: Terraform TFLint

on:
  workflow_call:

    inputs:

      module_name:
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:

  tflint:

    runs-on: self-hosted

    container:

      # Official Image
      # https://github.com/terraform-linters/tflint/pkgs/container/tflint
      image: ghcr.io/terraform-linters/tflint:v0.59.1
      options: --user 1000:1000

    defaults:

      run:
        shell: sh

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: TFLint Version
        run: tflint --version

      - name: Initialize and Run TFLint
        run: |

          echo "${{ inputs.module_name }}" | tr ',' '\n' | while IFS= read -r module; do
            module=$(echo "$module" | tr -d ' ')
            echo "--------------------------------------------"
            echo ">>> Processing module: $module"
            echo "--------------------------------------------"

            (
              cd "${module}/example" || exit 1
              tflint --init
              tflint --recursive --format compact
            )
          done

      - name: Workflow Summary
        if: always()
        run: |
          {
            echo "# Terraform TFLint"
            echo ""
            echo "| Item | Value |"
            echo "|------|-------|"
            echo "| Module | ${{ inputs.module_name }} |"
            echo "| Result | ${{ job.status }} |"
          } >> $GITHUB_STEP_SUMMARY