name: Terraform Apply

on:
  workflow_call:
    inputs:
      module_name:
        required: true
        type: string
    secrets:
      TF_API_TOKEN:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  id-token: write
  contents: read

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      module_list: ${{ steps.set-matrix.outputs.module_list }}
    steps:
      - id: set-matrix
        run: |
          MODULES=$(echo "${{ inputs.module_name }}" | jq -R -c 'split(",")')
          echo "module_list=$MODULES" >> $GITHUB_OUTPUT

  terraform-apply:
    needs: setup
    runs-on: self-hosted

    strategy:
      matrix:
        module: ${{ fromJson(needs.setup.outputs.module_list) }}
      fail-fast: false

    container:
      image: hashicorp/terraform:1.13.0
      options: --user 1000:1000

    defaults:
      run:
        shell: sh

    env:
      TF_IN_AUTOMATION: true
      TF_INPUT: false
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Terraform Version
        run: terraform version

      - name: Terraform Init
        working-directory: ${{ matrix.module }}/example
        run: |
          terraform init \
            -input=false \
            -no-color

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ matrix.module }}
          path: ${{ matrix.module }}/example

      - name: Terraform Apply
        working-directory: ${{ matrix.module }}/example
        run: |
          terraform apply \
            -input=false \
            -no-color \
            tfplan

      - name: Workflow Summary
        if: always()
        run: |
          {
            echo "# Terraform Apply"
            echo ""
            echo "| Item | Value |"
            echo "|------|-------|"
            echo "| Module | ${{ matrix.module }} |"
            echo "| Workspace | Terraform Cloud |"
            echo "| State | Remote |"
            echo "| Result | ${{ job.status }} |"
          } >> $GITHUB_STEP_SUMMARY